DROP TABLE IF EXISTS test_lock;
CREATE TABLE IF NOT EXISTS test_lock
(
   id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
   amount INTEGER NOT NULL
);

LOCK TABLE test_lock WRITE;
SELECT SLEEP(10);
UNLOCK TABLE test_lock;

LOCK TABLE test_lock READ;
SELECT SLEEP(10);
UNLOCK TABLE test_lock;
